### ISSUE TITLE
How to begin?

### ISSUE THREAD

**Issue by zenchantlive** [rsaryev/auto-copilot-cli#10]
I am unsure how to start this program. I have done the npm install. I just see a folder with node_modules. What command runs auto-copilot?

**Comment by zenchantlive** [comment]
apparently i just type auto-copilot into PowerShell lol

**Comment by rsaryev** [comment]
do you have windows?

**Comment by zenchantlive** [comment]
Yes i use windows.

**Comment by rsaryev** [comment]
https://www.onlogic.com/company/io-hub/how-to-enable-bash-for-windows-10-and-11/
