### ISSUE TITLE
Add support for GPT-4

### ISSUE THREAD

**Issue by Steadyx** [rsaryev/auto-copilot-cli#2]
Really cool project, I've been playing around with it and I think it's power can be overhauled if there could be an option to use GPT-4 instead of the current GPT-3.5, would be fun to play around with that and see what it can do.

**Comment by rsaryev** [comment]
Add support to change the model

**Comment by rsaryev** [comment]
Hello, please look at https://github.com/rsaryev/auto-copilot-cli/pull/6 🙏

**Comment by rsaryev** [comment]
Test please for example ```npx auto-copilot-cli create js file with implementation of binary search -a -m=gpt-4```

**Comment by rsaryev** [comment]
Good!
